//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agora
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentVote
    {
        public int CommentVoteID { get; set; }
        public Nullable<int> CommentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int VoteValue { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
    }
}
