//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agora
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainListTV
    {
        public int PostID { get; set; }
        public string PostTitle { get; set; }
        public string Username { get; set; }
        public string CommunityName { get; set; }
        public string PostText { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> VoteCount { get; set; }
    }
}
